export const seededAcademicModules = [
  {
    id: 'cn6000',
    academicYear: '2025/6',
    code: 'CN6000',
    title: 'Mental Wealth: Professional Life 3 (Project)',
    level: 6,
    term: 1,
    grade: null,
    status: 'In Progress',
    assessments: [
      'Project Material - Presentation/Project Plan (10 mins), Demonstration, Poster and Viva (25%)',
      'Project Report (10,000 words) (75%)',
    ],
  },
  {
    id: 'cn6001',
    academicYear: '2025/6',
    code: 'CN6001',
    title: 'Enterprise Architecture and Cloud Computing',
    level: 6,
    term: 1,
    grade: null,
    status: 'In Progress',
    assessments: ['Continuous assessment with practical tasks and group case work (100%)'],
  },
  {
    id: 'cn6004',
    academicYear: '2025/6',
    code: 'CN6004',
    title: 'Project Management',
    level: 6,
    term: 1,
    grade: 93,
    status: 'Pass',
    assessments: ['Coursework (2000 words) (50%)', 'Time-constrained assignment (1 hour) (50%)'],
  },
  {
    id: 'cn6021',
    academicYear: '2025/6',
    code: 'CN6021',
    title: 'Advanced Topics in AI & Data Science',
    level: 6,
    term: 1,
    grade: null,
    status: 'In Progress',
    assessments: ['Group task + individual evaluation + presentation (100%)'],
  },
  {
    id: 'cn6022',
    academicYear: '2025/6',
    code: 'CN6022',
    title: 'Big Data Infrastructure and Manipulation',
    level: 6,
    term: 1,
    grade: 88,
    status: 'Pass',
    assessments: ['Big Data project report (3000 words) + presentation (100%)'],
  },
  {
    id: 'cn5000',
    academicYear: '2024/5',
    code: 'CN5000',
    title: 'Database Systems',
    level: 5,
    term: 1,
    grade: 87,
    status: 'Pass',
    assessments: ['Continuous assessment + presentation (100%)'],
  },
  {
    id: 'cn5001',
    academicYear: '2024/5',
    code: 'CN5001',
    title: 'Business Intelligence Analysis',
    level: 5,
    term: 1,
    grade: 89,
    status: 'Pass',
    assessments: ['Group case-study solution tasks (100%)'],
  },
  {
    id: 'cn5005',
    academicYear: '2024/5',
    code: 'CN5005',
    title: 'Data Structures and Algorithms',
    level: 5,
    term: 1,
    grade: 78,
    status: 'Pass',
    assessments: ['Continuous practical tasks (100%)'],
  },
  {
    id: 'cn5009',
    academicYear: '2024/5',
    code: 'CN5009',
    title: 'Mental Wealth: Professional Life 2',
    level: 5,
    term: 1,
    grade: 84,
    status: 'Pass',
    assessments: ['Placement report + presentation + career development (100%)'],
  },
  {
    id: 'cn5021',
    academicYear: '2024/5',
    code: 'CN5021',
    title: 'Programming for Data Science',
    level: 5,
    term: 1,
    grade: 92,
    status: 'Pass',
    assessments: ['Practical tasks + in-class test (100%)'],
  },
  {
    id: 'cn5022',
    academicYear: '2024/5',
    code: 'CN5022',
    title: 'Artificial Intelligence',
    level: 5,
    term: 1,
    grade: 86,
    status: 'Pass',
    assessments: ['AI case practical + in-class test (100%)'],
  },
  { id: 'cn4000', academicYear: '2023/4', code: 'CN4000', title: 'Information Systems Modelling and Design', level: 4, term: 1, grade: 91, status: 'Pass', assessments: ['Portfolio (100%)'] },
  { id: 'cn4001', academicYear: '2023/4', code: 'CN4001', title: 'Software Development', level: 4, term: 1, grade: 98, status: 'Pass', assessments: ['Portfolio (100%)'] },
  { id: 'cn4002', academicYear: '2023/4', code: 'CN4002', title: 'Computer Systems and Networks', level: 4, term: 1, grade: 84, status: 'Pass', assessments: ['Portfolio (100%)'] },
  { id: 'cn4003', academicYear: '2023/4', code: 'CN4003', title: 'Web Technologies', level: 4, term: 1, grade: 93, status: 'Pass', assessments: ['Coursework (100%)'] },
  { id: 'cn4004', academicYear: '2023/4', code: 'CN4004', title: 'Maths for Computing', level: 4, term: 1, grade: 81, status: 'Pass', assessments: ['Portfolio (100%)'] },
  { id: 'cn4005', academicYear: '2023/4', code: 'CN4005', title: 'Mental Wealth: Professional Life 1 (IT Project Pitching)', level: 4, term: 1, grade: null, status: 'Pass', assessments: ['Portfolio (100%)'] },
  { id: 'cn6100', academicYear: '2025/6', code: 'CN6100', title: 'Data Ethics and Governance', level: 6, term: 2, grade: null, status: 'Planned', assessments: ['Case study and policy draft (100%)'] },
  { id: 'cn6101', academicYear: '2025/6', code: 'CN6101', title: 'Advanced Full Stack Systems', level: 6, term: 2, grade: null, status: 'Planned', assessments: ['Implementation project + viva (100%)'] },
]

